### ISSUE TITLE
log4jscanwin utility is not compatible with 64 bit

### ISSUE THREAD

**Issue by Rajeshbhard84** [Qualys/log4jscanwin#1]
Hi Qualys Team,

The log4jscanwin utility is not compatible with Win 64 bit. I ran on W10 64 bit

C:\<>\log4jscanwin-master\log4jscanwin-master>Log4jScanner.exe /scan /report_sig
This version of C:\Rajesh\log4jscanwin-master\log4jscanwin-master\Log4jScanner.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

Thanks,

**Comment by romw** [comment]
Which SKU of Windows are you running the utility on?  We haven't encountered any 64-bit specific issues in our internal testing.

Was this a custom build by chance?  I haven't been able to attempt to build the utility across various flavors of Windows with VS 2019.  My own dev box is Win10 Pro (64-bit).

Thanks in advance.

**Comment by Rajeshbhard84** [comment]
I tried on 2 W10 64 bit machine.
1) OS MS Win 10 Enterprise // Ver 10.0.19042 Build 19042 
2) OS MS Win 10 Home // Ver 10.0.19042 Build 19042 

Thanks

**Comment by romw** [comment]
Okay, I'll go double check on one of our Win10 64-bit Enterprise boxes.  I developed this tool against 19044 on a 64-bit system.

What processor type is your system running on? Intel? AMD? ARM64?

**Comment by romw** [comment]
A new build is up with native x64 support:
https://github.com/Qualys/log4jscanwin/releases/download/1.2.17/Log4jScanner-1.2.17.zip
