### ISSUE TITLE
Add script to run accorss an active directory environment 

### ISSUE THREAD

**Issue by Publicvoid0** [Qualys/log4jscanwin#11]
It would be great if anyone could come up with a way to execute the scanner accross an AD environment with hundreds of servers.

**Comment by romw** [comment]
That would be a bit outside my scope.

I'll gladly add any contributions to the project that can be audited and somebody is willing to put in the public domain.

**Comment by seanosullivanuk** [comment]
This isn't my best work, but I quickly put together a working script that copies the .exe locally, scans, outputs the results to a central shared folder and then cleans up after itself. (I'm using PDQ Deploy to deploy it across the network).
https://gist.github.com/seanosullivanuk/29a01e7581bf49c06b4e1f570016dedd

**Comment by Publicvoid0** [comment]
I have also created a script that executes the scanner accross all servers in an Active Directory Environment https://github.com/Publicvoid0/AD_Domain_Qualys_log4jScanner
