### ISSUE TITLE
No entries in the log4j_findings.out report

### ISSUE THREAD

**Issue by pawelodz** [Qualys/log4jscanwin#14]
After generating the report: log4j_findings.out I don't have any entries in the files. Why?

**Comment by Stalmashenko** [comment]
same result

**Comment by romw** [comment]
That usually means that the scanner didn't find anything vulnerable to report.  If you know of a vulnerability in a  file on your system, I would very much like to get a sample of the file.

**Comment by Stalmashenko** [comment]
Thanks a lot!

ср, 22 дек. 2021 г., 00:52 pawelodz ***@***.***>:
