### ISSUE TITLE
Scan Results Not getting saved

### ISSUE THREAD

**Issue by varunc85** [Qualys/log4jscanwin#17]
When we run this scanner locally, its automatically getting closed after completion. Therefore, we are not able to view/save results. can someone confirm where these results are stored?

**Comment by jonathanwo** [comment]
on Windows - check in %ProgramData%/Qualys there should be an .out file

**Comment by DJ-pnnl** [comment]
I noticed that only the /report_sig produced a .out file. If I run the Log4JScanner executable in a regular command prompt a new window is opened and I'm not able to view the results. If I run command prompt as an admin and run the scanner, the window doesn't go away and I am able to see the results.

**Comment by BondUniverse** [comment]
I'm running into the same issue.  Also, I noticed that the .out file has 3 ascii characters at the beginning (I think they may be causing issues with our RMM being able to check for specific words in the file).

Ideally, being able to have a file created for the other reports and/or having the output show in the command prompt that the program is being executed from (not another command prompt window as is being done now) so I can grab the contents programmatically, would be a huge help.

**Comment by Banjo-sys** [comment]
As a workaround Iam writing the Output into a File, converting it to UTF8 and then loading it into a variable.
Not a beautiful way but it works.

Sample Code:

Start-Process -FilePath $Scanner -ArgumentList "/scan","/report_pretty" -WorkingDirectory "C:\Windows\Temp\Qualys\Log4jScanner\x64" -Wait -RedirectStandardOutput "C:\windows\Temp\Qualys\Report.json" -RedirectStandardError "C:\windows\Temp\Qualys\Errors.txt"

Get-Content "C:\windows\Temp\Qualys\Report.json" -Encoding Unicode | Set-Content -Encoding UTF8 "C:\windows\Temp\Qualys\Report-utf8.json" -Force

Get-Content "C:\windows\Temp\Qualys\Report-utf8.json" | Write-Output

$ScanResult=Get-Content -Raw -Path "C:\windows\Temp\Qualys\Report-utf8.json" | ConvertFrom-Json

**Comment by romw** [comment]
I've updated the Readme.md file to stress the need to run the tool from an elevated command prompt.  Certain versions of Windows disconnect the input/output streams of commands when running commands that require elevated privileges from regular command prompts.
