### ISSUE TITLE
no compiled binary for 2.1.17 prerelease

### ISSUE THREAD

**Issue by johnmccash** [Qualys/log4jscanwin#5]
There's no compiled binary for the 2.1.7 prerelease that was put up 20 hours ago...

**Comment by romw** [comment]
See:
https://github.com/Qualys/log4jscanwin/releases/download/1.2.17/Log4jScanner-1.2.17.zip

Sorry about the wait, our code-signing cert vendor is having some hiccups and we were having to jump through a few hoops.  I suspect it has been a stressful week across the industry.

Thanks in advance.
