### ISSUE TITLE
Ran New Scan Still No Detections For QID 376160

### ISSUE THREAD

**Issue by MilesinCSAA** [Qualys/log4jscanwin#8]
Hello,

this is the same as the previous issue. we ran the new version of the scan and we still see no detections on QID 376160 despite output files being present listing vulnerable log4j.

**Comment by surbo** [comment]
We are seeing the same issues as above.
In checking the folder path c:\ProgramData\Qualys the following files are listed.
log4j_findings.out = (Found multiple paths with JNDI Class)
status.txt = (Run status : Success)

This output was from the Log4jScanner.exe version 1.2.17

**Comment by romw** [comment]
Yeah, we figured out our detection issue.  Last week was hectic in the lead up to both the signatures release and this utility being open sourced.  A dev on the signature team requested I make a change, and I failed to acknowledge the request even though I made the change.

Needless to say, the signatures were looking for the old tag, while the utility is writing out the new tag.  We identified the issue(s), as it affects more than one QID, and the signatures are being updated as we speak.

This issue affects QID 376160, QID 376195, and QID 376193.

We expect to see the fixed signatures drop on Monday IST (India Standard Time).

**Comment by surbo** [comment]
@romw thanks for the update.  Do you know what time on Monday IST?

**Comment by romw** [comment]
@surbo I'm told Monday morning IST.  I'm spit balling between 11pm tonight to 2am Monday Morning PST.

**Comment by MilesinCSAA** [comment]
Thank you Rom

**Comment by surbo** [comment]
@romw - Can you update this post when the fix is updated.  I saw this is closed now and I don't think the issue is resolved yet.  Thanks again. We appreciate the hard work you and the team have been doing.
