### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by surbo** [Qualys/log4jscanwin#9]
Would it be possible to include the host name in the output of log4j_findings.out? 

Thanks.

**Comment by romw** [comment]
I don't think I can add a machines host name to log4j_findings.out without breaking the signature teams ability to process the results.  However, I can modify the JSON reports however you like.

> log4jscanner.exe /scan /report > log4j_findings_json.out

That command would generate a JSON-based report which should be able to be parsed easily by powershell or python.

> log4jscanner.exe /scan /report_pretty > log4j_findings_json.out

That command would generate a Human readable JSON-based report which should be able to be parsed easily by powershell or python.

Is there anything else people would want to see added to the JSON based reports?

**Comment by pawelodz** [comment]
Hello. Where was saved use frendly report? Is olnly shoewed on scan screen?

**Comment by romw** [comment]
> Hello. Where was saved use frendly report? Is olnly shoewed on scan screen?

If you execute:
> log4jscanner.exe /scan /report_pretty > aa.txt

A aa.txt file should be created in the current directory with the results of the scan.

**Comment by subv3rsive** [comment]
Why can't I get this thing to pipe to output? The report is always blank. Even tried piping stdout and stderror to logs.

**Comment by romw** [comment]
By chance are you attempting to launch the scanner from an un-elevated command prompt?

I noticed, on somebody else's machine, that if you attempt to launch the scanner from an unelevated command prompt some Windows versions will spawn a new command prompt from a different process which will disappear after the command finishes execution.

Try the piping and redirections from an elevated command prompt.
